### ISSUE TITLE
Konsola klienta automatycznego

### ISSUE THREAD

**Issue by salberski** [DevelopersOrganizationFork/monitor-console#1]
Będzie to appka w postaci konsoli windowsowej.
Komunikacja z Monitorem odbywać się będzie za pomocą RESTa.

Potrzeba będzie zaimplementowania mechanizmu autoryzacji (najprawdopodobniej będą to tokeny przesyłane przez resta)

Wątek co jakiś czas będzie wołał RESTa (po stronie monitora) który zwróci top 10 obciążonych komputerów. (Potrzebna do tego będzie struktura danych, którą trzeba dokładnie zdefiniować, poczekamy aż @KamilSzelag sprawdzi co może jeszcze wyciągnąć z sensora i w jakiej postaci)

Wszyscy są już gdzieś obsadzeni, więc tutaj zostaje robota dla @ArturKiszka i @MateuszSak

**Comment by salberski** [comment]
@ArturKiszka i @obserwator (Mateusz Sak)
Póki co, możecie tak jak @mdrobny zamockować sobie prostą strukturę danych z pomiarami i sprawdzić:
1. Sortowanie tabeli po kolumnach;
 w jaki sposób wykonać można będzie sortowanie (po wartościach obciążenia CPU, memory, network)
1. Odświeżanie tabeli;
   żeby nie było to dopisywanie kolejnych linii do konsoli, ale żeby zadziałał mechanizm odświeżający i generujący na nowo tabele w statycznym miejscu (co określony interwał czasowy - tak jak działa watch na linuxie)
2. Zaimplementować form do logowania

**Comment by ArturKiszka** [comment]
ok

**Comment by obserwator** [comment]
Na chwilę obecną odświeżanie i sortowanie gotowe.
Zgodnie z formatem danych z tego [issue](https://github.com/DevelopersOrganizationFork/monitor-back/issues/15)
